### ISSUE TITLE
Re-upload the files in the folder named r_labelstyle

### ISSUE THREAD

**Issue by sridhar391** [ik9999/r_labelstyle#3]
Expected Behaviour:
1. Download the r_labelstye zip using https://github.com/ik9999/r_labelstyle/archive/master.zip link or download it from http://restya.com/board/apps/r_labelstyle
2. Extract the zip in the app folder of the Restyaboard and the `r_abelstyle` folder will be there 

Current Behaviour
1. After downloading the zip, while extracting the zip the `r_labelstyle-master` folder has been created and not `r_labelstyle`

Possible Solution:
Zip the files under the `r_labelstyle` name and upload it

**Comment by ik9999** [comment]
@sridhar391 
https://github.com/ik9999/r_labelstyle/releases/download/v1.0/dist.zip
Is this what you require?

**Comment by sridhar391** [comment]
Yes. Thank You.
